---
# tasks file for f5_Volume_Utlilization

- name: Collect Disk details
  bigip_command:
    commands:
     - bash -c df -h
    provider: "{{f5_provider}}"
  delegate_to: localhost
  check_mode: no
  register: disk_usage

- name: Print disk_usage
  debug:
    msg: "{{disk_usage.stdout_lines}}"
- name: Update an incident
  snow_record:
    username: admin
    password: qf1ViCiEMSk0
    instance: dev95938
    state: present
    number: "{{incident_num}}"
    data:
      work_notes : "{{disk_usage.stdout}}"
      close_code: "Solved (Permanently)"
      close_notes: "Resolved by Ansible Tower Automation"
      state: 6
      #state: 6
    #register: incidentupdate
    
# - name: Print incident update
#   debug:
#     var: incidentupdate.record.state
