---
# tasks file for f5_Device_Volume_Utilization

    - name: Find out playbooks path
      shell: pwd
      register: playbook_path_output
    - name: "Generic Playbook"
      Net_Connect:
        JumpServer: "{{ ansible_Jumpserver | default ('') }}"
        J_Username: "{{ J_username | default(D_username) }}"
        J_Password: "{{ J_password | default(D_password) }}"
        IP: "{{ ansible_host }}"
        D_Username: "{{ D_username }}"
        D_Password: "{{ D_password }}"
        Interface: "{{ interface | default('Null') }}"
        DeviceType: "{{ DeviceType | default('f5_ltm') }}"
        path: "{{ playbook_path_output.stdout }}"
        Type: "{{ Type | default('Volume_Utilization') }}"
      register: output
      #ignore_errors: True
      #no_log: False
    - debug:
         msg: "{{ output.meta }}"
      when: output is not changed
    - fail:
         msg: "{{ output.meta }}"
      when: output is changed
