---
# tasks file for f5_Volume_Utlilization

- name: Find out playbooks path
  shell: pwd
  register: playbook_path_output

- name: Collect Disk details
  F5_Volume_Utilization:
    IP: "{{ansible_host}}"
    user: "{{ansible_user}}"
    password: "{{ansible_password}}"
    JumpServer: "{{jumpserver | default('')}}"
    j_username: "{{j_username | default(ansible_user)}}"
    j_password: "{{j_password | default(ansible_password)}}"
    path: "{{ playbook_path_output.stdout }}"
  register: Volume_Utilization_Output

