---
# tasks file for snow_update
- name: Get specific Static Path binding for given EPG
  aci_static_binding_to_epg:
    host:  "{{ host }}"
    username: "{{ username }}"
    password:  "{{ password }}"
    tenant:  "{{ tenant }}"
    ap: "{{ ap }}"
    epg:  "{{ epg }}"
    interface_type:  "{{ interface_type }}"
    pod_id:  "{{ pod_id }}"
    leafs:  "{{ leafs }}"
    interface:  "{{ item }}"
    state: query
    use_ssl: no
    validate_certs: no
    timeout: 300
  delegate_to: localhost
  register: query_result
  with_items: "{{interface}}"

- name: SNOW work log Update
  snow_record:
    username: "{{snow_username}}"
    password: "{{snow_password}}"
    instance: "{{snow_instance}}"
    state: present
    table: change_request
    number: "{{change_number}}"
    data:
      work_notes: "Current status of Interface : \n\n Interface = {{ item.current[0].fvRsPathAtt.attributes.dn}} \n VLAN Number(s) = {{ \n\n item.current[0].fvRsPathAtt.attributes.encap }} \n\n "
  with_items: "{{ query_result.results}}"

- name: SNOW ticket status changing
  snow_record:
    username: "{{snow_username}}"
    password: "{{snow_password}}"
    instance: "{{snow_instance}}"
    state: present
    table: change_request
    number: "{{change_number}}"
    data:     
      state: "{{item}}"
      close_code: Successful
      close_notes: "Automation Closed Change"
  with_items:
      - 0
      - 3

